### ISSUE TITLE
sha3 v0.11.0-rc.8 fails to build on Rust 1.91.1

### ISSUE THREAD

**Issue by Osspial** [RustCrypto/hashes#795]
Building `sha3-0.11.0-rc.8` fails with the following error:

```
   Compiling sha3 v0.11.0-rc.8
error[E0432]: unresolved import `digest::block_buffer::BlockSizes`
  --> /Users/aubs/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sha3-0.11.0-rc.8/src/block_api.rs:10:5
   |
10 |     block_buffer::BlockSizes,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^ no `BlockSizes` in the root

For more information about this error, try `rustc --explain E0432`.
```

I tried building for `aarch64-apple-darwin` and `wasm32-unknown-unknown` and got this error - I'm not sure if it shows up on different targets.

**Comment by newpavlov** [comment]
See https://github.com/RustCrypto/traits/issues/2316

**Comment by M0dEx** [comment]
> See [RustCrypto/traits#2316](https://github.com/RustCrypto/traits/issues/2316)

I am afraid to say nothing about that issue or the associated PRs/releases resolved this. This still happens at latest released versions of the libraries in question.
