### ISSUE TITLE
sha2 0.10: HmacSha256::new_from_slice ... unsatisfied trait bounds

### ISSUE THREAD

**Issue by tobymurray** [RustCrypto/hashes#332]
just tried upgrading from sha2 v0.9 to v0.10 and I can't build because of the log below. Caveat: I'm relatively new to Rust and don't have a great sense of what I'm doing, so I might be doing something silly. I'm trying to treat an environment variable as a constant, and feed that into the hash. I have the environment variable loaded with:
```
lazy_static! {
  pub static ref API_SECRET: String = env::var("API_SECRET").expect("Shopify application API secret has not been specified");
}
```
Then, mostly following compiler suggestions to make the types happy, I'm invoking:
```
HmacSha256::new_from_slice(&*statics::API_SECRET.clone().into_bytes())
```

I'm open to this being a silly way to have done this, as it stands this worked on v0.9 and crashes with 0.10. Any suggestions for how I could fix this?

```
   Compiling rust-project v0.1.0 (/home/toby/git/rust/rust-project)
error[E0599]: the function or associated item `new_from_slice` exists for struct `Hmac<CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>>`, but its trait bounds were not satisfied
  --> src/hmac_request_guard.rs:41:32
   |
41 |           let mut hasher = HmacSha256::new_from_slice(&*statics::API_SECRET.clone().into_bytes())
   |                                        ^^^^^^^^^^^^^^ function or associated item cannot be called on `Hmac<CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>>` due to unsatisfied trait bounds
   |
  ::: /home/toby/.cargo/registry/src/github.com-1ecc6299db9ec823/digest-0.10.0/src/core_api/wrapper.rs:20:1
   |
20 | / pub struct CoreWrapper<T>
21 | | where
22 | |     T: BufferKindUser,
23 | |     T::BlockSize: IsLess<U256>,
...  |
27 | |     buffer: BlockBuffer<T::BlockSize, T::BufferKind>,
28 | | }
   | | -
   | | |
   | | doesn't satisfy `_: BlockInput`
   | | doesn't satisfy `_: FixedOutputDirty`
   | | doesn't satisfy `_: hmac::digest::FixedOutput`
   | |_doesn't satisfy `_: hmac::digest::Reset`
   |   doesn't satisfy `_: hmac::digest::Update`
   |
  ::: /home/toby/.cargo/registry/src/github.com-1ecc6299db9ec823/hmac-0.11.0/src/lib.rs:80:1
   |
80 | / pub struct Hmac<D>
81 | | where
82 | |     D: Update + BlockInput + FixedOutput + Reset + Default + Clone,
83 | |     D::BlockSize: ArrayLength<u8>,
...  |
87 | |     opad_digest: D,
88 | | }
   | |_- doesn't satisfy `_: NewMac`
   |
   = note: the following trait bounds were not satisfied:
           `CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>: hmac::digest::Update`
           which is required by `Hmac<CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>>: NewMac`
           `CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>: BlockInput`
           which is required by `Hmac<CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>>: NewMac`
           `CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>: hmac::digest::FixedOutput`
           which is required by `Hmac<CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>>: NewMac`
           `CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>: hmac::digest::Reset`
           which is required by `Hmac<CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>>: NewMac`
           `CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>: FixedOutputDirty`
           which is required by `Hmac<CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>>: NewMac`

error[E0277]: the trait bound `CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>: hmac::digest::Update` is not satisfied
  --> src/hmac_request_guard.rs:41:20
   |
41 |         let mut hasher = HmacSha256::new_from_slice(&*statics::API_SECRET.clone().into_bytes())
   |                          ^^^^^^^^^^ the trait `hmac::digest::Update` is not implemented for `CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>`
   |
note: required by a bound in `Hmac`
  --> /home/toby/.cargo/registry/src/github.com-1ecc6299db9ec823/hmac-0.11.0/src/lib.rs:82:8
   |
82 |     D: Update + BlockInput + FixedOutput + Reset + Default + Clone,
   |        ^^^^^^ required by this bound in `Hmac`

error[E0277]: the trait bound `CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>: BlockInput` is not satisfied
  --> src/hmac_request_guard.rs:41:20
   |
41 |         let mut hasher = HmacSha256::new_from_slice(&*statics::API_SECRET.clone().into_bytes())
   |                          ^^^^^^^^^^ the trait `BlockInput` is not implemented for `CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>`
   |
note: required by a bound in `Hmac`
  --> /home/toby/.cargo/registry/src/github.com-1ecc6299db9ec823/hmac-0.11.0/src/lib.rs:82:17
   |
82 |     D: Update + BlockInput + FixedOutput + Reset + Default + Clone,
   |                 ^^^^^^^^^^ required by this bound in `Hmac`

error[E0277]: the trait bound `CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>: hmac::digest::Reset` is not satisfied
  --> src/hmac_request_guard.rs:41:20
   |
41 |         let mut hasher = HmacSha256::new_from_slice(&*statics::API_SECRET.clone().into_bytes())
   |                          ^^^^^^^^^^ the trait `hmac::digest::Reset` is not implemented for `CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>`
   |
note: required by a bound in `Hmac`
  --> /home/toby/.cargo/registry/src/github.com-1ecc6299db9ec823/hmac-0.11.0/src/lib.rs:82:44
   |
82 |     D: Update + BlockInput + FixedOutput + Reset + Default + Clone,
   |                                            ^^^^^ required by this bound in `Hmac`

error[E0277]: the trait bound `CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>: FixedOutputDirty` is not satisfied
  --> src/hmac_request_guard.rs:41:20
   |
41 |         let mut hasher = HmacSha256::new_from_slice(&*statics::API_SECRET.clone().into_bytes())
   |                          ^^^^^^^^^^ the trait `FixedOutputDirty` is not implemented for `CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>`
   |
   = note: required because of the requirements on the impl of `hmac::digest::FixedOutput` for `CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>>`
note: required by a bound in `Hmac`
  --> /home/toby/.cargo/registry/src/github.com-1ecc6299db9ec823/hmac-0.11.0/src/lib.rs:82:30
   |
82 |     D: Update + BlockInput + FixedOutput + Reset + Default + Clone,
   |                              ^^^^^^^^^^^ required by this bound in `Hmac`

warning: unused import: `Mac`
 --> src/hmac_request_guard.rs:2:18
  |
2 | use hmac::{Hmac, Mac, NewMac};
  |                  ^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `NewMac`
 --> src/hmac_request_guard.rs:2:23
  |
2 | use hmac::{Hmac, Mac, NewMac};
  |                       ^^^^^^

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
warning: `rust-project` (bin "rust-project") generated 2 warnings
error: could not compile `rust-project` due to 5 previous errors; 2 warnings emitted
```

**Comment by newpavlov** [comment]
Have you updated `hmac` to v0.12?

**Comment by tobymurray** [comment]
Ah - no, I did not. That's a requirement for 0.10? I'll give that a shot now.

The most naive try of bumping `sha2` from `0.9` to `0.10` and `hmac` from `0.11` to `0.12` yields:

```
   Compiling rust-project v0.1.0 (/home/toby/git/rust/rust-project)
error[E0432]: unresolved import `hmac::NewMac`
 --> src/hmac_request_guard.rs:2:23
  |
2 | use hmac::{Hmac, Mac, NewMac};
  |                       ^^^^^^ no `NewMac` in the root

error[E0308]: mismatched types
  --> src/hmac_request_guard.rs:54:23
   |
54 |         match hasher.verify(&hmac) {
   |                             ^^^^^ expected struct `GenericArray`, found struct `Vec`
   |
   = note: expected reference `&GenericArray<u8, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>`
              found reference `&Vec<u8>`
note: return type inferred to be `&GenericArray<u8, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>` here
  --> src/hmac_request_guard.rs:24:80
   |
24 |       async fn from_request(request: &'r Request<'_>) -> Outcome<Self, Self::Error> {
   |  ___________________________________________________________________________________^
25 | |         // 1. Get the entire query string in one shot
26 | |         let query_string = match request.uri().query() {
27 | |             None => return Outcome::Failure((Status::Unauthorized, HmacParamError::NoQueryString)),
...  |
57 | |         }
58 | |     }
   | |_____^

Some errors have detailed explanations: E0308, E0432.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `rust-project` due to 2 previous errors
```
Looking at the [changelog](https://github.com/RustCrypto/MACs/blob/e8ca014e4c565c441071edc2a204addaa14c9dea/hmac/CHANGELOG.md#0120-2021-12-07) I don't see it mentioned and it seems like [NewMac](https://docs.rs/hmac/0.11.0/hmac/trait.NewMac.html) has been removed in a minor version bump?

I'll have to look at this closer later, as it stands it seems like a trait I was using disappeared.

**Comment by newpavlov** [comment]
Yes, the `NewMac` trait was removed during merge of `crypto-mac` into `digest`. Initialization methods are now part of the [`Mac`](https://docs.rs/digest/latest/digest/trait.Mac.html) convenience trait. As you can see in the docs, the `verify` method now requires an array. If  you want to check code from a byte slice, then you should use the `verify_slice` method.

I will try to expand changelogs later, but, in general, I recommend taking a look at examples in the crate docs, e.g. the [`hmac` docs](https://docs.rs/hmac) reflect the `NewMac` and `verify` changes.

**Comment by tobymurray** [comment]
Just looked back at this now, trivial update. Deleted `NewMac` as a use statement, changed my use of `verify` to `verify_slice` and off to the races. Thanks!
