### ISSUE TITLE
sha-1 0.9.6 fails to cross build on aarch64-unknown-linux-musl

### ISSUE THREAD

**Issue by jszwedko** [RustCrypto/hashes#273]
This appears to work on 0.9.5.

```
➜  hash git:(master) ✗ cat Cargo.toml
[package]
name = "hash"
version = "0.1.0"
authors = ["Jesse Szwedko <jesse@szwedko.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha-1 = "0.9.6"

➜  hash git:(master) ✗ cat src/main.rs
fn main() {
    println!("Hello, world!");
}

➜  hash git:(master) ✗ cross build --target aarch64-unknown-linux-musl
   Compiling cpufeatures v0.1.1
   Compiling generic-array v0.14.4
error[E0432]: unresolved import `libc::HWCAP_AES`
  --> /cargo/registry/src/github.com-1ecc6299db9ec823/cpufeatures-0.1.1/src/aarch64.rs:55:21
   |
55 |               pub use libc::$hwcap;
   |                       ^^^^^^^^^^^^ no `HWCAP_AES` in the root
...
70 | / __expand_check_macro! {
71 | |     ("aes",  HWCAP_AES),  // Enable AES support.
72 | |     ("sha2", HWCAP_SHA2), // Enable SHA1 and SHA256 support.
73 | |     ("sha3", HWCAP_SHA3), // Enable SHA512 and SHA3 support.
74 | | }
   | |_- in this macro invocation
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `cpufeatures`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by tarcieri** [comment]
Definitely related to #268.

I'm not quite sure what's at fault here though... possibly the `libc` crate? It looks like musl defines `HWCAP_AES` and it was added about 5 years ago:

https://github.com/bminor/musl/blob/4433115/arch/aarch64/bits/hwcap.h#L4

Edit: definitely looks like a problem with the `libc` crate. Here's the PR which added support for glibc, which was merged a little over a year ago:

https://github.com/rust-lang/libc/pull/1638/files

It looks like a similar PR would be needed to add them here (possibly even copy/paste from the glibc bindings):

https://github.com/rust-lang/libc/blob/master/src/unix/linux_like/linux/musl/b64/aarch64/mod.rs

It looks like there's even a TODO for it here (although not a GitHub issue, AFAICT):

https://github.com/rust-lang/libc/blob/ed1399a/libc-test/semver/TODO-linux.txt

In the meantime we can gate CPU feature detection on `target_env = "gnu"` until `libc` has been updated.

**Comment by tarcieri** [comment]
Opened an issue on the `libc` crate:

https://github.com/rust-lang/libc/issues/2171

I'd say for now stick with `sha-1` v0.9.5 and I will try to release a v0.9.7 that addresses this in the next day or so.

**Comment by jszwedko** [comment]
Thanks for the quick response! I'll keep an eye on that issue.

**Comment by tarcieri** [comment]
@jszwedko I just published `cpufeatures `v0.1.2 which I think should both address this and allow feature detection to work on musl targets.

Can you try `cargo update -p cpufeatures` and let me know if it fixes the problem?

(Sidebar: we should probably add some musl targets to CI)

**Comment by jszwedko** [comment]
@tarcieri this looks great, thanks for the quick fix!
