### ISSUE TITLE
Regression in blake2 v0.10.0 - new `reset` feature fails to compile

### ISSUE THREAD

**Issue by tommilligan** [RustCrypto/hashes#341]
Introduced in https://github.com/RustCrypto/hashes/commit/75298d36b9400654ad3bbee072b59c5ffed27aa4

A new feature flag, `reset`, was introduced to gate features where hashers can reset their internal state (nit: this was not noted in the changelog as a breaking change).

This feature does not appear to be tested in the github actions CI, and consequently is broken.

Compiling `master` locally with rust 1.57.0 I see:

```
$ cargo build --features reset                                                                                                                                                                                                                                                        ✔
   Compiling blake2 v0.10.0 (/home/tom/personal/hashes/blake2)
error[E0308]: mismatched types
   --> blake2/src/macros.rs:407:53
    |
394 |         impl<OutSize> FixedOutputReset for $name<OutSize>
    |              ------- this type parameter
...
407 |                 core.finalize_variable_core(buffer, out);
    |                                                     ^^^ expected struct `UInt`, found type parameter `OutSize`
    |
   ::: blake2/src/lib.rs:143:1
    |
143 | blake2_mac_impl!(Blake2bMac, Blake2bVarCore, U64, "Blake2b MAC function");
    | ------------------------------------------------------------------------- in this macro invocation
    |
    = note: expected mutable reference `&mut GenericArray<u8, UInt<UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>, B0>>`
               found mutable reference `&mut GenericArray<u8, OutSize>`
    = note: this error originates in the macro `blake2_mac_impl` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> blake2/src/macros.rs:407:53
    |
394 |         impl<OutSize> FixedOutputReset for $name<OutSize>
    |              ------- this type parameter
...
407 |                 core.finalize_variable_core(buffer, out);
    |                                                     ^^^ expected struct `UInt`, found type parameter `OutSize`
    |
   ::: blake2/src/lib.rs:173:1
    |
173 | blake2_mac_impl!(Blake2sMac, Blake2sVarCore, U32, "Blake2s MAC function");
    | ------------------------------------------------------------------------- in this macro invocation
    |
    = note: expected mutable reference `&mut GenericArray<u8, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>`
               found mutable reference `&mut GenericArray<u8, OutSize>`
    = note: this error originates in the macro `blake2_mac_impl` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0308`.
error: could not compile `blake2` due to 2 previous errors
```

I would be happy to submit a PR if some guidance can be given on the most appropriate fix, I'll see if I can work out a potential fix now.
